name       : tinyxml2
version    : 6.2.0
release    : 5
source     :
    - https://github.com/leethomason/tinyxml2/archive/6.2.0.tar.gz : cdf0c2179ae7a7931dba52463741cf59024198bbf9673bf08415bcb46344110f
license    : Zlib
component  : system.utils
summary    : TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs
description: |
    TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
