name       : tinyxml2
version    : 4.0.1
release    : 3
source     :
    - https://github.com/leethomason/tinyxml2/archive/4.0.1.tar.gz : 14b38ef25cc136d71339ceeafb4856bb638d486614103453eccd323849267f20
license    : Zlib
component  : system.utils
summary    : TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs.
description: |
    TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
