name       : tinyxml2
version    : 8.0.0
release    : 7
source     :
    - https://github.com/leethomason/tinyxml2/archive/8.0.0.tar.gz : 6ce574fbb46751842d23089485ae73d3db12c1b6639cda7721bf3a7ee862012c
license    : Zlib
component  : system.utils
summary    : TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs
description: |
    TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
