name       : tinyxml2
version    : 2.2.0
release    : 2
source     :
    - https://github.com/leethomason/tinyxml2/archive/2.2.0.tar.gz : f891224f32e7a06bf279290619cec80cc8ddc335c13696872195ffb87f5bce67
license    : Zlib
summary    : TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs.
description: |
    TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
