name       : tinyxml2
version    : 6.0.0
release    : 4
source     :
    - https://github.com/leethomason/tinyxml2/archive/6.0.0.tar.gz : 9444ba6322267110b4aca61cbe37d5dcab040344b5c97d0b36c119aa61319b0f
license    : Zlib
component  : system.utils
summary    : TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs
description: |
    TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
