name       : tinyxml2
version    : 7.0.1
release    : 6
source     :
    - https://github.com/leethomason/tinyxml2/archive/7.0.1.tar.gz : a381729e32b6c2916a23544c04f342682d38b3f6e6c0cad3c25e900c3a7ef1a6
license    : Zlib
component  : system.utils
summary    : TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs
description: |
    TinyXML-2 is a simple, small, efficient, C++ XML parser that can be easily integrated into other programs.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
